config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new' 
  get  '/users/:id/photos', to: 'users#photos'

  root 'info_pages#home'
  get 'privacy' => 'info_pages#privacy'
  get 'terms' => 'info_pages#terms'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :users, :stores # index[GET], show[GET], new[GET]->create[POST](no view), edit[GET]->update[PATCH](no view), destroy[DELETE](no view via ajax)
  resources :photos, only: [:create, :destroy]
  resources :maps, only: [:show]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :ratings, only: [:new, :create, :edit, :update]
  resources :hours, only: [:new, :create, :edit, :update]
  

end

app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to :map
  has_many   :ratings, dependent: :destroy
  has_many   :hours, dependent: :destroy
  has_many   :photos, dependent: :destroy
  validates  :name,
              presence: true,
              length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates  :email,
              presence: true,
              length: { maximum: 255 },
              format: { with: VALID_EMAIL_REGEX },
              uniqueness: { case_sensitive: false }
  has_secure_password #uses bcrypt gem to create hash
                      #gives hashed password_digest(saved in password_digest column in db),
                      #password & password confirmation attributes, including prescence and matching validation
                      #authenticate method, returns user from db when pass is correct
  has_attached_file :profile_pic,
                     default_url: ":style-no-truck.png",
                     styles: {profile: "190X190#",
                              thumb: "45X45#"},
                     url: "/assets/stores/:id/:style/:basename.:extension",
                     path: ":rails_root/public/assets/stores/:id/:style/:basename.:extension"
  validates_attachment_content_type :profile_pic,
                                     content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates :password,
             presence: true,
             length: { minimum: 6 },
            allow_nil: true
  validates :city,
             presence: true,
             length: { maximum: 255 }
  validates :state,
             presence: true,
             length: { maximum: 255 }
  validates :lat, length: { maximum: 11 }
  validates :lng, length: { maximum: 11 }
  validates :store_type, length: { maximum: 255 }
end


def Store.digest(string)
  cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
  BCrypt::Password.create(string, cost: cost)
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  #before_action :check_claim_status, only:[:new,:create,:edit,:update]
  before_action :logged_in_user, only: [:edit,:update]
  
  def show
    @store = Store.find(params[:id])
    unless @store
      redirect_to root_url
    end
    if current_user
      @rating = current_user.ratings.find_by(store_id: @store)
    end
    gon.rabl
  end
  
  def new
    @store = Store.new
  end
  
  def create
    @store = Store.find(params[:id])
  end
  
  def edit
    @store = Store.find(params[:id])
    @hour = Hour.new
  end
  
  def update
    @store = Store.find(params[:id])
    if @store.update_attributes(store_params)
      flash[:success] = 'Profile successfully updated'
    else
      flash[:danger] = 'Profile could not be updated'
    end
    redirect_to edit_store_path(@store)
  end
  
    private
     def store_params
       params.require(:store).permit(:name,:email,:address,:city,:state,:profile_pic)
     end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_map.html.erb
<div id="mapWrapStore">
	<div id="gmap" data-map="<%="#{@store.lat}|#{@store.lng}"%>" data-type="profile" data-zoom=15></div>
</div>

app/views/stores/_rate.html.erb
<div class="rating-wrap">
	<%= form_for :rating, url: ratings_path do |f| %>
		<%= hidden_field_tag :store_id, @store.id %>
		<%= hidden_field_tag :user_id, current_user.id %>
		<div class="stars clearfix">
			<div>
				<ul class="stars-0" id="starList">
					<li id="stars-1"><input id="rating-1" class="rating" name="rating" type="radio" value=1 /></li>
					<li id="stars-2"><input id="rating-2" class="rating" name="rating" type="radio" value=2 /></li>
					<li id="stars-3"><input id="rating-3" class="rating" name="rating" type="radio" value=3 /></li>
					<li id="stars-4"><input id="rating-4" class="rating" name="rating" type="radio" value=4 /></li>
					<li id="stars-5"><input id="rating-5" class="rating" name="rating" type="radio" value=5 /></li>
				</ul>
			</div>
		</div>
		<div class="text-wrap">
			<textarea autocomplete="off" id="comment" name="comment" placeholder="Write a review.."></textarea>
		</div>
		<%= f.submit "Post Review", class: "btnSmall" %>
	<% end %>
</div>

app/views/stores/_rate_no_user.erb
<div class="rating-wrap">
	<%= form_for :rating, url: ratings_path do |f| %>
		<%= hidden_field_tag :store_id, @store.id %>
		<div class="stars clearfix">
			<div>
				<ul class="stars-0" id="starList">
					<li id="stars-1"><input id="rating-1" class="rating" name="rating" type="radio" value=1 /></li>
					<li id="stars-2"><input id="rating-2" class="rating" name="rating" type="radio" value=2 /></li>
					<li id="stars-3"><input id="rating-3" class="rating" name="rating" type="radio" value=3 /></li>
					<li id="stars-4"><input id="rating-4" class="rating" name="rating" type="radio" value=4 /></li>
					<li id="stars-5"><input id="rating-5" class="rating" name="rating" type="radio" value=5 /></li>
				</ul>
			</div>
		</div>
		<div class="text-wrap">
			<textarea autocomplete="off" id="comment" name="comment" placeholder="Write a review.."></textarea>
		</div>
		<%= f.submit "Post Review", class: "btnSmall" %>
	<% end %>
</div>

app/views/stores/_rated.html.erb
<div class="rating-wrap">
	<%= form_for @rating, url: rating_path(@rating) do |f| %>
		<%= hidden_field_tag :store_id, @store.id %>
		<%= hidden_field_tag :user_id, current_user.id %>
		<div class="stars clearfix">
			<div>
				<ul class="stars-<%= @rating.rating %>" id="starList">
					<li id="stars-1"><input id="rating-1" class="rating" name="rating" type="radio" value=1 /></li>
					<li id="stars-2"><input id="rating-2" class="rating" name="rating" type="radio" value=2 /></li>
					<li id="stars-3"><input id="rating-3" class="rating" name="rating" type="radio" value=3 /></li>
					<li id="stars-4"><input id="rating-4" class="rating" name="rating" type="radio" value=4 /></li>
					<li id="stars-5"><input id="rating-5" class="rating" name="rating" type="radio" value=5 /></li>
				</ul>
			</div>
		</div>
		<div class="text-wrap">
			<textarea autocomplete="off" id="comment" name="comment" placeholder="Write a review.."><%= @rating.comment %></textarea>
		</div>
		<%= f.submit "Edit Review", class: "btnSmall" %>
	<% end %>
</div>

app/views/stores/_sign_up.html.erb
<div id="logBox">
	<p class="question">Have you been to this brewery?</p>
	<%= link_to "Sign up to add review!", signup_path, class: "redBtn" %>
</div>

app/views/stores/_store_admin.html.erb
<h1>Edit <%= @store.name %></h1>
<div class="hoursWrap">
	<div class="editWrap">
		<h3>General</h3>
		<%= form_for @store do |f| %>
			<%= render 'shared/error_messages' %>
			<%= f.label :name %>
			<%= f.text_field :name %>
			<%= f.label :email %>
			<%= f.text_field :email %>
			<%= f.label :address %>
			<%= f.text_field :address %>
			<%= f.label :city %>
			<%= f.text_field :city %>
			<%= f.label :state %>
			<%= f.text_field :state %>
			<div class="profilePicBack">
				<div class="previewPicWrap">
				 	<%= image_tag(@store.profile_pic.url(:profile), alt: @store.name, class: "picPreview")%> 
				</div>
			</div>
			<%= f.file_field :profile_pic, class: "uploadPic" %>
			<%= f.submit "Edit basic", class: "editBtn" %>
		<% end %>
	</div>
	<div class="hourWrap">
		<h3>Hours</h3>
		<% if !@store.hours.blank? %>
			<%= render 'hours/edit_hours' %>
		<% else %>
			<%= render 'hours/new_hours' %>
		<% end %>
	</div>
</div>

app/views/stores/_store_feed.html.erb
<div class="feedPane">
	<% @store.ratings.each do |rating| %>
		<div class="feedWrap clearfix">
			<div class="thumbWrap">
				<%= image_tag rating.user.profile_pic(:thumb), class: "userThumb", alt: rating.user.name %>
			</div>
			<div class="userLink">
				<%= link_to rating.user.name, rating.user, class: "thumbLink" %>
				<span class="headDescrip">rated</span><span class="star star-<%= rating.rating %>"><span class="headDescrip">'s</span>
						<b><%= rating.created_at.to_s(:easy_date) %></b>
					</span>
				<span class="commentText"><%= rating.comment %></span>
			</div>
		</div>
	<% end %>
</div>

app/views/stores/_times.html.erb
<% @store.hours.each do |t| %>
<% #strftime("%I:%M%p") %>
<% days= ["mon","tue","wed","thu","fri","sat","sun"] %>
 <ul class="time-listings">
	<!-- MONDAY -->
    <li class="time-list">
		<b class="time-day">MONDAY:</b>
		<span><%= t.mon_o_hour %></span><span>:</span><span><%= t.mon_o_min %></span><span><%= t.mon_o_meridiem%></span>
		<span> - </span>
		<span><%= t.mon_c_hour %></span><span>:</span><span><%= t.mon_c_min %></span><span><%= t.mon_c_meridiem%></span>
	</li>
	<!-- TUESDAY -->
	<li class="time-list">
		<b class="time-day">TUESDAY:</b>
		<span><%= t.tue_o_hour %></span><span>:</span><span><%= t.tue_o_min %></span><span><%= t.tue_o_meridiem%></span>
		<span> - </span>
		<span><%= t.tue_c_hour %></span><span>:</span><span><%= t.tue_c_min %></span><span><%= t.tue_c_meridiem%></span>
	</li>
	<!-- WEDNESDAY -->
	<li class="time-list">
		<b class="time-day">WEDNESDAY:</b>
		<span><%= t.wed_o_hour %></span><span>:</span><span><%= t.wed_o_min %></span><span><%= t.wed_o_meridiem%></span>
		<span> - </span>
		<span><%= t.wed_c_hour %></span><span>:</span><span><%= t.wed_c_min %></span><span><%= t.wed_c_meridiem%></span>
	</li>
	<!-- THURSDAY -->
	<li class="time-list">
		<b class="time-day">THURSDAY:</b>
		<span><%= t.thu_o_hour %></span><span>:</span><span><%= t.thu_o_min %></span><span><%= t.thu_o_meridiem%></span>
		<span> - </span>
		<span><%= t.thu_c_hour %></span><span>:</span><span><%= t.thu_c_min %></span><span><%= t.thu_c_meridiem%></span>
	</li>
	<!-- FRIDAY -->
	<li class="time-list">
		<b class="time-day">FRIDAY:</b>
		<span><%= t.fri_o_hour %></span><span>:</span><span><%= t.fri_o_min %></span><span><%= t.fri_o_meridiem%></span>
		<span> - </span>
		<span><%= t.fri_c_hour %></span><span>:</span><span><%= t.fri_c_min %></span><span><%= t.fri_c_meridiem%></span>
	</li>
	<!-- SATURDAY -->
	<li class="time-list">
		<b class="time-day">SATURDAY:</b>
		<span><%= t.sat_o_hour %></span><span>:</span><span><%= t.sat_o_min %></span><span><%= t.sat_o_meridiem%></span>
		<span> - </span>
		<span><%= t.sat_c_hour %></span><span>:</span><span><%= t.sat_c_min %></span><span><%= t.sat_c_meridiem%></span>
	</li>
	<!-- SUNDAY -->
	<li class="time-list">
		<b class="time-day">SUNDAY:</b>
		<span><%= t.sun_o_hour %></span><span>:</span><span><%= t.sun_o_min %></span><span><%= t.sun_o_meridiem%></span>
		<span> - </span>
		<span><%= t.sun_c_hour %></span><span>:</span><span><%= t.sun_c_min %></span><span><%= t.sun_c_meridiem%></span>
	</li>
 </ul>
<% end %>

app/views/stores/edit.html.erb
<% provide(:title, @store.name) %>

<% if current_user.admin %>
	<%= render 'admin' %>
<% elsif current_user.store_admin %>
	<%= render 'store_admin' %>
<% end %>

app/views/stores/show.html.erb
<% provide(:title, @store.name) %>
<%= render 'map' %>
<div class="headWrap clearfix">
	<div class="profilePicWrap">
		<%= image_tag(@store.profile_pic.url(:profile), alt: @store.name, class: "profilePic") %>
	</div>
	<div class="infoWrap">
		<h1 class="usernameHead"><%= @store.name %></h1>
		<% if current_user && !current_user.store_admin %>
			<div class="claimWrap">
				<i class="fa fa-hand-o-up"></i><%= link_to "Claim this brewery", new_store_path, class: "claimLink" %>
			</div>
		<% elsif current_user && current_user.store_admin && current_user.store_id == @store.id %>
			<div class="claimWrap">
				<i class="fa fa-pencil"></i><%= link_to "Edit #{@store.name}", edit_store_path(@store), class: "claimLink", method: :get %>
			</div>
		<% end %>
		<span class="store-address head-text">
			<i class="fa fa-industry"></i><%= @store.address %>, <%= @store.city %>, <%= @store.state %>
			<br/>
			<span class="starhead star-<%= @store.ratings.sum(:rating) %>"><%= @store.ratings.sum(:rating) %>.0 (<%= pluralize(@store.ratings.count, "Review") %>)</span>
		</span>
	</div>
</div>
<div class="profileContainer clearfix">
	<div class="leftCnter">
		<% if current_user %>
			<% if @rating %>
				<%= render 'rated' %>
			<% else %>
				<%= render 'rate' %>
			<% end %>
		<% else %>
			<!-- <%= render 'sign_up' %> -->
			<%= render 'rate_no_user' %>
		<% end %>
		<%= render 'store_feed' %>
	</div>

	<div class="rightCnter">
		<div class="info-wrap">
			<!-- <span class="store-address head-text">
		    <span class="starhead star-<%= @store.ratings.sum(:rating) %>"><%= @store.ratings.sum(:rating) %>.0 (<%= pluralize(@store.ratings.count, "Review") %>)</span>
			<br/>
			<i class="fa fa-industry"></i><%= @store.address %>, <%= @store.city %>, <%= @store.state %>
			</span> -->
			<span class="store-phone head-text"></span>
			<span class="store-website head-text"></span>
		</div>
		<%= render 'times' %>
	</div>
</div>