config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new' 
  get  '/users/:id/photos', to: 'users#photos'

  root 'info_pages#home'
  get 'privacy' => 'info_pages#privacy'
  get 'terms' => 'info_pages#terms'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :users, :stores # index[GET], show[GET], new[GET]->create[POST](no view), edit[GET]->update[PATCH](no view), destroy[DELETE](no view via ajax)
  resources :photos, only: [:create, :destroy]
  resources :maps, only: [:show]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :ratings, only: [:new, :create, :edit, :update]
  resources :hours, only: [:new, :create, :edit, :update]
  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  has_many :ratings
  has_many :photos, dependent: :destroy
  validates :name,
             presence: true,
             length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
             presence: true,
             length: { maximum: 255 },
             format: { with: VALID_EMAIL_REGEX },
             uniqueness: { case_sensitive: false }
  has_secure_password #uses BCrypt gem to create hash, #gives hashed password_digest(saved in password_digest column in db), #password & password confirmation attributes, including prescence and matching validation, #authenticate method, returns user from db when password is correct
  validates :password,
             presence: true,
             length: { minimum: 6 },
             allow_nil: true #for edit->update....has_secure_password will reject nil for signup
  has_attached_file :profile_pic,
                     default_url: ":style-no-profile.png",
                     styles: {profile: "190x190#", thumb: "45x45#"},
                     url: "/assets/users/:id/:style/:basename.:extension",
                     path: ":rails_root/public/assets/users/:id/:style/:basename.:extension"
                     #validates_attachment_presence :profile_pic
                     #validates_attachment_size :profile_pic, less_than: 100.megabytes
  validates_attachment_content_type :profile_pic,
                                     content_type: ["image/jpeg", "image/jpg", "image/png", "image/gif"]

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost

    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(self.remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    self.reset_sent_at < 2.hours.ago
  end

    private

    def downcase_email
      self.email = email.downcase
    end

    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token) #created before user is saved and will be written to db upon save
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page]).per_page(30)
  end

  def show
    @user = User.find(params[:id])
  end

  def photos
    @user = User.find(params[:id])
    @photo = current_user.photos.build if logged_in?
    @photos = current_user.photos
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      log_in @user
      flash[:success] = "Welcome to Foodtruck Maps!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile successfully updated"
      redirect_to edit_user_path(@user)
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :profile_pic, :password, :password_confirmation)
    end

    def correct_user
     @user = User.find(params[:id])
     redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<!-- USER RENDER @users TO ACCESS -->

app/views/users/_user_feed.html.erb
<div class="feedPane">
	<% @user.ratings.each do |rating| %>
		<div class="feedWrap clearfix">
				<div class="thumbWrap">
					<%= image_tag rating.store.profile_pic(:thumb), class: "userThumb", alt: rating.user.name %>
				</div>
				<div class="userLink">
					<%= link_to rating.store.name, rating.store, class: "thumbLink", method: :get %>
					<span class="headDescrip">got rated</span><span class="star star-<%= rating.rating %>"><span class="headDescrip">'s</span>
					<b><%= rating.created_at.to_s(:easy_date) %></b>
					</span>
					<span class="commentText"><%= rating.comment %></span>
				</div>
		</div>
	<% end %>
</div>

app/views/users/_user_left_pane.html.erb
<div class="sideMenu">
	<ul class="menuListing">
		<% select.each do |m,v| %>
			<li id="<%= m %>li" class="<%= v ? 'menuSelected' : ''%>">
				<% if m.to_s == 'ratings' %>
					<%= link_to "#{m.capitalize}", @user, class: "menuLink" %>
				<% else %>
					<%= link_to "#{m.capitalize}", "/users/#{@user.id}/#{m}", class: "menuLink", method: :get %>
				<% end %>
			</li>
		<% end %>
	</ul>
</div>

app/views/users/_user_photo_feed.html.erb
<% if @photos %>
	<% @photos.each do |p| %>
		<% if !p.photo.blank? %>
		<div class="feedWrap clearfix">
			<div class="thumbWrap">
				<%= image_tag @user.profile_pic.url(:thumb), class: "userThumb", alt: @user.name %>
			</div>
			<div class="userLink">
				<%= link_to @user.name, @user, class: "thumbLink", method: :get %>
				<span class="commdate">added a photo on <b><%= p.created_at.to_s(:easy_date) %></b></span>
			</div>
			<div class="commentPic"><%= image_tag p.photo.url(:feed) %></div>
		</div>
		<% end %>
	<% end %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, @user.name + " | Edit")%>

<div class="editWrap">
	<h1 class="signHead">Edit Profile</h1>
	<div class="editForm">
		<%= form_for @user, html: {multipart: true } do |f| %>
			<%= render 'shared/error_messages' %>
			
			<%= f.label :name %>
			<%= f.text_field :name %>
			
			<%= f.label :email %>
			<%= f.email_field :email %>
			
			<%= f.label :password %>
			<%= f.password_field :password %>
			
			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>
			
			<div class="profilePicBack">
				<div class="previewPicWrap">
				 	<%= image_tag(@user.profile_pic.url(:profile), alt: @user.name, class: "picPreview") %> 
				</div>
			</div>
			<%= f.file_field :profile_pic, class: "uploadPic" %>
			
			<%= f.submit "Update profile", class: "editBtn" %>
		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All beer drinkers')%>
<h1 class="usernameHead">Beer Lovers</h1>

<%= will_paginate %>

<ul class="users">
	<% @users.each do |user| %>
		<li class="clearfix">
			<div class="thumbWrap">
				<%= image_tag(user.profile_pic.url(:thumb), alt: user.name, class: "userThumb") %>
			</div>
			
				<%= link_to user.name, user, class: "thumbLink" %>
				
				<% if current_user.admin? && !current_user?(user) %>
					<span class="pipe">|</span><%= link_to "Delete", user, class: "deleteLink", method: :delete, data: {confirm: "Are you sure?"}%>
				<% end %>
		</li>
	<% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<div class="signUpWrap">
	<h1 class="signHead">Sign Up</h1>
	<div class="signUpForm">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name, placeholder: "Username" %>

			<%= f.label :email %>
			<%= f.email_field :email, placeholder: "Email" %>

			<%= f.label :password %>
			<%= f.password_field :password, placeholder: "Password" %>

			<%= f.label :password_confirmation, "Confimration" %>
			<%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>

			<%= f.submit "Sign Up", class: "postBtn" %>
			<% end %>
	</div>
</div>

app/views/users/photos.html.erb
<% provide(:title, "#{@user.name}s photos") %>
<div id="userDivide">
</div>
<div class="headWrap clearfix">
	<div class="profilePicWrap">
		<%= image_tag(@user.profile_pic.url(:profile), alt: @user.name, class: "profilePic") %>
	</div>
	<div class="infoWrap">
		<h1 class="usernameHead"><%= @user.name %></h1>
		<div class="userLinksWrap">
		<% if @user == current_user %>
			<i class="fa fa-pencil"></i><%= link_to "Edit", edit_user_path(@user), class: "userlink", id: "editLink", method: :get %>
			<i class="fa fa-users"></i><%= link_to "More Drinkers", users_path, class: "userlink", id: "moreLink" %>
			<i class="fa fa-beer"></i><% if @user.store_id %>
				<%= link_to "Your Brewery", store_path(@user.store_id), class: "userlink", id: "brewLink", method: :get %>
			<% end %>
		<% end %>
		</div>
	</div>
</div>
<div class="profileContainer clearfix">
	<div class="leftCnter">
		<% if logged_in? %>
			<%= render 'photos/user_photo_form' %>
		<% end %>
		<%= render 'user_photo_feed' %>
	</div>
	
	<div class="rightCnter">
		<%= render 'user_left_pane', select: {ratings: false, photos: true} %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div id="userDivide">
</div>
<div class="headWrap clearfix">
	<div class="profilePicWrap">
		<%= image_tag(@user.profile_pic.url(:profile), alt: @user.name, class: "profilePic") %>
	</div>
	<div class="infoWrap">
		<h1 class="usernameHead"><%= @user.name %></h1>
		<div class="userLinksWrap">
		<% if @user == current_user %>
			<i class="fa fa-pencil"></i><%= link_to "Edit", edit_user_path(@user), class: "userlink", id: "editLink", method: :get %>
			<i class="fa fa-users"></i><%= link_to "More Drinkers", users_path, class: "userlink", id: "moreLink" %>
			<i class="fa fa-beer"></i><% if @user.store_id %>
				<%= link_to "Your Brewery", store_path(@user.store_id), class: "userlink", id: "brewLink", method: :get %>
			<% end %>
		<% end %>
		</div>
	</div>
</div>
<div class="profileContainer clearfix">
	
	<div class="leftCnter">
		<%= render 'user_feed' %>
	</div>
	
	<div class="rightCnter">
		<%= render 'user_left_pane', select: {ratings: true, photos: false} %>
	</div>
</div>