config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new' 
  get  '/users/:id/photos', to: 'users#photos'

  root 'info_pages#home'
  get 'privacy' => 'info_pages#privacy'
  get 'terms' => 'info_pages#terms'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :users, :stores # index[GET], show[GET], new[GET]->create[POST](no view), edit[GET]->update[PATCH](no view), destroy[DELETE](no view via ajax)
  resources :photos, only: [:create, :destroy]
  resources :maps, only: [:show]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :ratings, only: [:new, :create, :edit, :update]
  resources :hours, only: [:new, :create, :edit, :update]
  

end

app/views/layouts/_city_menu.erb
	<li><%= link_to "Los Angeles", "#" %></li>
	<li><%= link_to "San Francisco", "#" %></li>
	<li><%= link_to "San Jose", "#" %></li>
	<li><%= link_to "Portland", "#" %></li>
	<li><%= link_to "Denver", "/maps/denver", method: :get %></li>
	<li><%= link_to "Chicago", "#" %></li>

app/views/layouts/_city_menu.html.erb
	<li><%= link_to "Los Angeles", "/maps/los-angeles", method: :get %></li>
	<li><%= link_to "San Francisco", "/maps/san-francisco", method: :get %></li>
	<li><%= link_to "San Jose", "/maps/san-jose", method: :get %></li>
	<li><%= link_to "Portland", "/maps/portland", method: :get %></li>
	<li><%= link_to "Denver", "/maps/denver", method: :get %></li>
	<li><%= link_to "Chicago", "/maps/chicago", method: :get %></li>

app/views/layouts/_footer.html.erb
<div id="footer">
	<ul>
		<li><%= link_to "Privacy", privacy_path %></li>
		<li><%= link_to "Terms", terms_path %></li>
	</ul>
</div>

app/views/layouts/_header.html.erb
<header>
	<div id="headWrap" class="clearfix">
		<div id="headLogo">
			<%= link_to image_tag("foodtruck-logo.png", class: "head-icon-image", alt: "Foodtruck Maps Logo"), '/', class: "head-icon-link", method: :get %>
		</div>
		<div id="navWrap">
			<nav>
				<ul id="navList">
					<!-- <li id="searchList"><input id="search" type="text" autocomplete="off" placeholder="Find" /></li> -->
					<li><i class="fa fa-home" aria-hidden="true"></i> <%= link_to "Home", root_path, method: :get, class: "homeLink"%></li>
					<% if logged_in? %>
						<li><i class="fa fa-user" aria-hidden="true"></i> <%= link_to "Profile", user_path(@current_user) %></li>
						<li><i class="fa fa-sign-out" aria-hidden="true"></i> <%= link_to "Log Out", logout_path, method: :delete, class: "logoutLink" %></li>
					<% else %>
						<li><i class="fa fa-user-plus" aria-hidden="true"></i> <%= link_to "Sign Up", signup_path, class: "signinLink" %></li>
						<li><i class="fa fa-sign-in" aria-hidden="true"></i> <%= link_to "Log In", login_path, class: "loginLink" %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= do_title(yield(:title)) %></title>
    <%= Gon::Base.render_data({}) %>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCrNHfpG00Mz7LYzHZkSZD0X0bgugkOzmY"></script>
    <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
        <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
        </script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    
    <div class="container tripleBorders">

    	<% flash.each do |type,message| %>
    		<div class="<%= type %>">
    			<%= message %>
    		</div>
    	<% end %>

    	<%= yield %>
    </div>

    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>